name: REScout
options:
  bundleIdPrefix: com.AlexMohit
  xcodeVersion: "15.4"
  deploymentTarget:
    iOS: "17.0"
settings:
  PRODUCT_BUNDLE_IDENTIFIER: com.AlexMohit.REScout
  INFOPLIST_FILE: ios/ValueREScout/Info.plist
  GENERATE_INFOPLIST_FILE: false
  DEVELOPMENT_TEAM: "523MJL63MC"
  CODE_SIGN_STYLE: Automatic
  SWIFT_VERSION: "5.9"
  CURRENT_PROJECT_VERSION: "1"
  MARKETING_VERSION: "1.0"
  ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
targets:
  REScout:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ios/ValueREScout
    settings:
      INFOPLIST_FILE: ios/ValueREScout/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.AlexMohit.REScout
      DEVELOPMENT_TEAM: "523MJL63MC"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
